In [1]:
import numpy as np
import gym # pip intall gym
import random

In [2]:
env = gym.make('FrozenLake-v1', is_slippery = False)

In [3]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

qtable = np.zeros((state_space_size, action_space_size))
qtable


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
#Hyper Parameters

total_episodes = 10000
learning_rate = 0.2 # 0-1
max_steps = 100
gamma = 0.99  #discount factor

epsilon = 1
max_epsilon = 1
min_epsilon = 0.01
decay_rate = 0.001

In [5]:
rewards = []

for episode in range(total_episodes):
    state = env.reset()[0]
    step = 0
    done = False
    total_rewards = 0
    
    for step in range(max_steps):
        if random.uniform(0,1) > epsilon:
            action = np.argmax(qtable[state][:]) #Exploit
        else:
            action = env.action_space.sample() #Explore
            
        new_state, reward, done, info,_ = env.step(action)
        
        max_new_state = np.max(qtable[new_state,:])
        # if type(state)!=int:
        #     state=state[0]
        print("state is ",state)
        print("action is ",action)
        
        # qtable[state,action] = qtable[state,action] + learning_rate*(reward+gamma*max_new_state-qtable[state,action])
        qtable[state][action] = qtable[state][action] + learning_rate*(reward+gamma*max_new_state-qtable[state][action])
        total_rewards += reward
        
        state = new_state
        if done:
            break
        
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)
    rewards.append(total_rewards)
        
print("Score:", str(sum(rewards)/total_episodes))


state is  0
action is  3
state is  0
action is  3
state is  0
action is  3
state is  0
action is  1
state is  4
action is  1
state is  8
action is  3
state is  4
action is  2
state is  0
action is  3
state is  0
action is  2
state is  1
action is  3
state is  1
action is  2
state is  2
action is  0
state is  1
action is  2
state is  2
action is  0
state is  1
action is  0
state is  0
action is  2
state is  1
action is  3
state is  1
action is  2
state is  2
action is  0
state is  1
action is  0
state is  0
action is  0
state is  0
action is  2
state is  1
action is  3
state is  1
action is  0
state is  0
action is  2
state is  1
action is  2
state is  2
action is  2
state is  3
action is  3
state is  3
action is  2
state is  3
action is  0
state is  2
action is  0
state is  1
action is  1
state is  0
action is  1
state is  4
action is  3
state is  0
action is  1
state is  4
action is  1
state is  8
action is  1
state is  0
action is  3
state is  0
action is  2
state is  1
action is  0


In [6]:
print(qtable)

[[0.94148015 0.93206535 0.95099005 0.94148015]
 [0.94148015 0.         0.96059601 0.95099005]
 [0.95099005 0.970299   0.95099005 0.96059601]
 [0.96059601 0.         0.94943592 0.95049191]
 [0.93152147 0.91729657 0.         0.94148015]
 [0.         0.         0.         0.        ]
 [0.         0.9801     0.         0.96059601]
 [0.         0.         0.         0.        ]
 [0.63048032 0.         0.69589765 0.93163666]
 [0.82232208 0.91659201 0.9801     0.        ]
 [0.970299   0.99       0.         0.970299  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.88991583 0.99       0.8543035 ]
 [0.9801     0.99       1.         0.9801    ]
 [0.         0.         0.         0.        ]]


In [7]:
# using q-table  to generate the optimum policy now



# Define the greedy policy
def greedy_policy(state):
    action = np.argmax(qtable[state][:])
    return action

# Generate the optimum policy
policy = np.zeros(env.observation_space.n, dtype=int)
for state in range(env.observation_space.n):
    policy[state] = greedy_policy(state)

# Print the optimum policy
print(policy)


[2 2 1 0 3 0 1 0 3 2 1 0 0 2 2 0]


In [8]:
env = gym.make("FrozenLake-v1", is_slippery=False,render_mode='human')
curr_state=env.reset()[0]
env.render()
while(1):
    next_state,reward,done,_,_=env.step(int(policy[curr_state]))
    # next_state,reward,done,_,_=env.step(2)
    curr_state=next_state
    print(curr_state)
    if curr_state==15:
        print("hurray we reached the goal")
        break


1
2
6
10
14
15
hurray we reached the goal


In [9]:
qtable[state,action] = qtable[state,action] + learning_rate*(reward+gamma*max_new_state-qtable[state,action])

In [10]:
env.reset()

for episode in range(5):
    state = env.reset()
    step = 0
    done = False
    
    print("Episode:", episode+1)
    
    for step in range(max_steps):
        action = np.argmax(qtable[state,:])
        new_state, reward, done, info = env.step(action)
        env.render()
        if done:
            
            print("Number of Steps:", step)
            break
        state = new_state
        
env.close()

Episode: 1


IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices